### ISSUE TITLE
Choosing files to copy

### ISSUE THREAD

**Issue by nomve** [tlvince/grunt-wiredep-copy#2]
Hi,
is there a reason you're skipping 'packages', and instead going for the files chosen by wiredep (like `'js': [], 'css': [],` etc.). The reason I'm asking is that wiredep ignores things like font files, even if they are listed in main, because it doesn't embed them into any file, or at least not that I managed to make it work. But if I just read all the main arrays from the packages object it works and all the dependencies are copied. It also works with overrides. Is there a gotcha that I'm not aware of?

**Comment by tlvince** [comment]
To be honest, its been a long time since I wrote and last used this package. However, I believe the intention was to mimic `wiredep`s behaviour and only copy the things it injects. You're right in that typically you'll have to write your own glue code for other assets, e.g. fonts. Happy to take a pull request if you think there's a case to change this behaviour. Feel free to reopen the issue is so.

**Comment by nomve** [comment]
I was just curious, but I have to say I didn't look at it in a while, so I'm not sure how it was resolved. If I come back to it, I'll let you know.
